version: "3"
# Listed here is the services we want to run.
# We can modify the folder name to build the service - ie look for context: ./parking -> its look for parking folder with Dockerfile inside
# We can change the port -> <EXPOSED PORT>:< INTERNAL PORT>, we uses exposed port to communicate to the service to make curl call or access from host
# You can comment other service block if u want to tryout the particular service

services:
  authentication:
    build:
      context: ./authentication
      args:
        ENVIRONMENT: local
    ports:
      - 5000:5000
    networks:
      gmp-net:
        aliases:
          - authentication

  authorizations:
    build:
      context: ./authorizations
      args:
        ENVIRONMENT: local
    ports:
      - 5010:5010
    networks:
      gmp-net:
        aliases:
          - authorizations

  consumer-users:
    build:
      context: ./consumer-users
      args:
        ENVIRONMENT: local
    ports:
      - 5020:5020
    networks:
      gmp-net:
        aliases:
          - consumer-users

  payments:
    build:
      context: ./payments
      args:
        ENVIRONMENT: local
    ports:
      - 5030:5030
    networks:
      gmp-net:
        aliases:
          - payments

  dashboard:
    build:
      context: ./dashboard
      args:
        ENVIRONMENT: local
    ports:
      - 5040:5040
    networks:
      gmp-net:
        aliases:
          - dashboard

  parking:
    build:
      context: ./parking
      args:
        ENVIRONMENT: local
    ports:
      - 5050:5050
    networks:
      gmp-net:
        aliases:
          - parking

  parking-session:
    build:
      context: ./parking-session
      args:
        ENVIRONMENT: local
    ports:
      - 5060:5060
    networks:
      gmp-net:
        aliases:
          - parking-session

  tariff-engine:
    build:
      context: ./tariff-engine
      args:
        ENVIRONMENT: local
    ports:
      - 5070:5070
    networks:
      gmp-net:
        aliases:
          - tariff-engine

  pass:
    build:
      context: ./pass
      args:
        ENVIRONMENT: local
    ports:
      - 5080:5080
    networks:
      gmp-net:
        aliases:
          - pass

  offer-engine:
    build:
      context: ./offer-engine
      args:
        ENVIRONMENT: local
    ports:
      - 5090:5090
    networks:
      gmp-net:
        aliases:
          - offer-engine

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      gmp-net:
        aliases:
          - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.3
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    networks:
      gmp-net:
        aliases:
          - kibana

volumes:
  mysql_data: {}
 
networks:
  gmp-net:
    driver: bridge